/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivityCard: typeof import('./src/components/activity/ActivityCard.vue')['default']
    ActivityFilter: typeof import('./src/components/activity/ActivityFilter.vue')['default']
    ActivityList: typeof import('./src/components/activity/ActivityList.vue')['default']
    ActivitySearch: typeof import('./src/components/activity/ActivitySearch.vue')['default']
    ActivitySidebar: typeof import('./src/components/layout/ActivitySidebar.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    CommentItem: typeof import('./src/components/comment/CommentItem.vue')['default']
    CommentReply: typeof import('./src/components/comment/CommentReply.vue')['default']
    CommentSection: typeof import('./src/components/comment/CommentSection.vue')['default']
    ConfirmDialog: typeof import('./src/components/dialog/ConfirmDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    InfoDialog: typeof import('./src/components/dialog/InfoDialog.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    MainSidebar: typeof import('./src/components/layout/MainSidebar.vue')['default']
    MyActivitiesPanel: typeof import('./src/components/activity/MyActivitiesPanel.vue')['default']
    MyActivityiesPanel: typeof import('./src/components/activity/MyActivityiesPanel.vue')['default']
    QuoteReference: typeof import('./src/components/comment/QuoteReference.vue')['default']
    RegisterDialog: typeof import('./src/components/activity/RegisterDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserAvatar: typeof import('./src/components/common/UserAvatar.vue')['default']
    UserHoverCard: typeof import('./src/components/common/UserHoverCard.vue')['default']
  }
}
